#!/usr/bin/env bash
sudo -v
echo "********************************************************************************"
echo "                           INSTALAÇÃO DO COMPOSER                               "
echo "********************************************************************************"
printf "\n"

if [ ! -f /usr/local/bin/composer ];
then
	curl -sS https://getcomposer.org/installer | php
	sudo mv composer.phar /usr/local/bin/composer

	echo -e "\nO Composer foi instalado com successo!"

else
	echo -e "\nO Composer já está instalado!"
fi